Taxonomy errors 5
openfoodfacts/openfoodfacts-server pull request #4096
Opened 2020-08-30 16:36 UTC by aleene

2020-09-07 17:58 UTC, aleene commented
@stephanegigandet what is the issue? There is no fail.

2020-09-11 01:37 UTC, svensven commented on taxonomies/additives.txt
> +en:E578, calcium gluconate
Guessing it doesn't like this.
2020-09-07T15:43:53.8871819Z Errors in the additives taxonomy definition:
2020-09-07T15:43:53.8909631Z ERROR - en:e578 is a parent of itself
2020-09-07T15:43:53.8910404Z Errors in the additives taxonomy definition at lib/ProductOpener/Tags.pm line 1618.
2020-09-07T15:43:54.1858128Z [additives] child process exited with code 25

2020-09-15 14:57 UTC, stephanegigandet requested changes
Putting descriptions / comments above entries is not supported.

description:en:CALCIUM CARBONATE is a chemical compound with the formula CaCO3.
comment:en:This entry must be doubled in the minerals and additives taxonomy (for the time being).
#<en:calcium
#en:E170(i)
<en:E170	<en:E170

If those are comments : just start the line with # .

If those are properties (like description:en: ) they need to be after the entry and all the synonyms.

2020-09-15 16:18 UTC, aleene commented
Note that I did it like that everywhere (all taxonomies).

2020-09-20 11:20 UTC, stephanegigandet approved these changes
Thank you!

2020-09-20 11:21 UTC, merged