Categories - move en: translation to top where it exists. For #4082
openfoodfacts/openfoodfacts-server pull request #4098
Opened 2020-08-30 20:49 UTC by svensven

2020-08-30 21:24 UTC, hangy approved these changes

2020-08-31 07:02 UTC, stephanegigandet commented on taxonomies/categories.txt
>  en:Unsalted French bread, Unsalted baguette
the English name is incorrect, it should be:


```suggestion
en:Traditional French baguette, French traditional baguette
```

2020-08-31 07:02 UTC, stephanegigandet commented on taxonomies/categories.txt
>  en:Chocolate cake with melting centre refrigerated
```suggestion
en:Chocolate cake with melting centre
```

2020-08-31 07:03 UTC, stephanegigandet commented on taxonomies/categories.txt
>  en:Reblochon cheese from cow's milk
```suggestion
en:Reblochon, Reblochon cheeses, Reblochon cheese from cow's milk
```

2020-08-31 07:04 UTC, stephanegigandet commented on taxonomies/categories.txt
>  en:Causses blue cheese from cow's milk
```suggestion
en:Causses blue cheeses, Causses blue cheese from cow's milk
```

2020-08-31 07:04 UTC, stephanegigandet commented on taxonomies/categories.txt
>  en:Brie de Meaux cheese from cow's milk
```suggestion
en:Brie de Meaux cheeses, Brie de Meaux cheese from cow's milk
```

2020-08-31 07:05 UTC, stephanegigandet commented on taxonomies/categories.txt
>  en:Brie de Melun cheese from cow's milk
```suggestion
en:Brie de Melun, Brie de Melun cheeses, Brie de Melun cheese from cow's milk
```

2020-08-31 07:05 UTC, stephanegigandet commented on taxonomies/categories.txt
>  en:Chaource cheese from cow's milk
```suggestion
en:Chaource, Chaource cheeses, Chaource cheese from cow's milk
```

2020-08-31 07:05 UTC, stephanegigandet commented on taxonomies/categories.txt
>  en:Langres cheese from cow's milk
```suggestion
en:Langres, Langres cheeses, Langres cheese from cow's milk
```

2020-08-31 07:06 UTC, stephanegigandet commented on taxonomies/categories.txt
>  en:Morbier cheese from cow's milk
```suggestion
en:Morbier, Morbier cheeses, Morbier cheese from cow's milk
```

2020-08-31 07:06 UTC, stephanegigandet commented on taxonomies/categories.txt
>  en:Saint-Marcellin cheese from cow's milk
```suggestion
en:Saint-Marcellin, Saint-Marcellin cheeses, Saint-Marcellin cheese from cow's milk
```

2020-08-31 07:07 UTC, stephanegigandet commented on taxonomies/categories.txt
>  en:Vacherin cheese or Mont d'or cheese from cow's milk
```suggestion
en:Mont d'Or, Mont d'Or cheeses, Vacherin cheese or Mont d'or cheese from cow's milk
```

2020-08-31 07:07 UTC, stephanegigandet commented on taxonomies/categories.txt
>  en:Livarot cheese from cow's milk
```suggestion
en:Livarot, Livarot cheeses, Livarot cheese from cow's milk
```

2020-08-31 07:08 UTC, stephanegigandet commented on taxonomies/categories.txt
>  en:Carré de l'Est cheese from cow's milk
```suggestion
en:Carré de l'Est, Carré de l'Est cheeses, Carré de l'Est cheese from cow's milk
```

2020-08-31 07:08 UTC, stephanegigandet commented on taxonomies/categories.txt
>  en:Saint-Nectaire cheese
```suggestion
en:Saint-Nectaire, Saint-Nectaire cheeses
```

2020-08-31 07:09 UTC, stephanegigandet commented on taxonomies/categories.txt
>  en:Raclette cheese from cow's milk
```suggestion
en:Raclette, Raclette cheeses, Raclette cheese from cow's milk
```

2020-08-31 07:09 UTC, stephanegigandet commented on taxonomies/categories.txt
>  en:Comté cheese from cow's milk
```suggestion
en:Comté, Comté cheeses, Comté cheese from cow's milk
```

2020-08-31 07:09 UTC, stephanegigandet commented on taxonomies/categories.txt
>  en:Uncured soft cheese spreadable around 30-40% fat flavoured (ex : garlic and herbs)
```suggestion
en:Uncured soft cheese spreadable around 30-40% fat flavoured
```

2020-08-31 07:10 UTC, stephanegigandet commented on taxonomies/categories.txt
> +fr:Fromages Ail et fines herbes, fromage ail et fines herbes type Boursin, Tartare
```suggestion
fr:Fromages Ail et fines herbes
```

2020-08-31 07:11 UTC, stephanegigandet commented on taxonomies/categories.txt
>  en:Almond grilled salted
```suggestion
en:Salted and grilled almonds, Grilled and salted almonds, Almond grilled salted
```

2020-08-31 07:12 UTC, stephanegigandet commented on taxonomies/categories.txt
>  en:Shepherd's pie with duck cooked
```suggestion
en:Shepherd's pie with duck
```

2020-08-31 07:13 UTC, stephanegigandet commented on taxonomies/categories.txt
>  en:Cooked ratatouille
```suggestion
en:Ratatouille
```

2020-08-31 07:13 UTC, stephanegigandet commented on taxonomies/categories.txt
>  en:Pork roast raw
```suggestion
en:Pork roasts
```

2020-08-31 07:16 UTC, stephanegigandet requested changes
A lot of the entries where French was first came from the French CIQUAL database, and the English translations were not good (too specific, or with commas etc.). I made suggestions to change them.

2020-08-31 14:09 UTC, svensven commented
Github's not letting me apply the suggestions, either individually or as a batch. it just says "This diff has recently been updated. Refresh and try again". Even tried in a different browser. :facepalm: 
Looks like my browser's trying to POST to ```https://github.com/openfoodfacts/openfoodfacts-server/pull/4098/apply_suggestions``` and getting a 404 back.

2020-08-31 18:39 UTC, stephanegigandet commented
> Github's not letting me apply the suggestions, either individually or as a batch. it just says "This diff has recently been updated. Refresh and try again". Even tried in a different browser.

I have this often on the taxonomies for some reason. :( Sorry for all the manual work.

2020-08-31 18:40 UTC, stephanegigandet approved these changes
Thank you!

2020-08-31 19:11 UTC, merged