Update ingredients.txt
openfoodfacts/openfoodfacts-server pull request #4131
Opened 2020-09-02 21:08 UTC by teolemon

2020-09-08 13:47 UTC, aleene requested changes
All the romanian deletes seem to be ok (checked with a translator).

2020-09-08 13:47 UTC, aleene commented on taxonomies/ingredients.txt
> +nl:uiensmaak
`uiensmaak` can be deleted, should be `uienaroma`.

2020-09-08 13:47 UTC, aleene commented on taxonomies/ingredients.txt
> -ro:fulgi de grâu
I think this is ok. https://www.sanovita.ro/fulgi-de-grau-500g-174.html

2020-09-08 13:47 UTC, aleene commented on taxonomies/ingredients.txt
> -ro:germeni de grâu
should be `germenii de grâu`

2020-09-08 13:47 UTC, aleene commented on taxonomies/ingredients.txt
> -ro:fulgi de orz
is ok

2020-09-08 13:47 UTC, aleene commented on taxonomies/ingredients.txt
>  ru:Овсяные хлопья
mixing romanian and german. keep the deleted version.

2020-09-08 13:47 UTC, aleene commented on taxonomies/ingredients.txt
> -ro:fibre de ovăz
is ok

2020-09-08 13:47 UTC, aleene commented on taxonomies/ingredients.txt
> -ro:fulgi de secară
is ok

2020-09-08 13:47 UTC, aleene commented on taxonomies/ingredients.txt
> -
what is wrong with this.

2020-09-08 13:47 UTC, aleene commented on taxonomies/ingredients.txt
> -ro:făină integrală de grâu
probably ok

2020-09-08 13:47 UTC, aleene commented on taxonomies/ingredients.txt
> -
is ok

2020-09-08 13:47 UTC, aleene commented on taxonomies/ingredients.txt
> -
?

2020-09-08 13:47 UTC, aleene commented on taxonomies/ingredients.txt
> -de:Vollkornreismehl
is ok?

2020-09-08 13:47 UTC, aleene commented on taxonomies/ingredients.txt
>  fi:vanilliinisokeri
german translation is ok

2020-09-08 13:47 UTC, aleene commented on taxonomies/ingredients.txt
> -ro:oligofructoză
why delete?

2020-09-08 13:47 UTC, aleene commented on taxonomies/ingredients.txt
> -
Is in principle OK. can be synonym of dextrose.

2020-09-08 13:47 UTC, aleene commented on taxonomies/ingredients.txt
> +nl:kokosvet
kokosvet is wrong, should be cacaovet

2020-09-08 13:47 UTC, aleene commented on taxonomies/ingredients.txt
> +de:Kakaobutter
Kakaobutter  this should be under cocoa butter

2020-09-08 13:47 UTC, aleene commented on taxonomies/ingredients.txt
> -ro:grăsime de cacao
looks ok

2020-09-08 13:47 UTC, aleene commented on taxonomies/ingredients.txt
> -ro:ciocolată cu lapte
ok

2020-09-08 13:47 UTC, aleene commented on taxonomies/ingredients.txt
> +de:kochendes Wasser
Does not sound ok, should be `Kochwasser`, kochendes wasser is water that is cooking (now)

2020-09-08 13:47 UTC, aleene commented on taxonomies/ingredients.txt
> -ro:gluten de grâu, gluten din grâu
ok?

2020-09-08 13:47 UTC, aleene commented on taxonomies/ingredients.txt
> -ro:banane uscate
?

2020-09-08 13:47 UTC, aleene commented on taxonomies/ingredients.txt
>  <en:apple
is ok

2020-09-08 13:47 UTC, aleene commented on taxonomies/ingredients.txt
> +en:organic cidre apple juice
what is happening here? wrong deletes.

2020-09-08 13:47 UTC, aleene commented on taxonomies/ingredients.txt
>  ru:финик, финики
the synonym should be kept. Has been found on products.

2020-09-08 13:47 UTC, aleene commented on taxonomies/ingredients.txt
> +fr:Poudre de fraise
should appear under strawberry powder

2020-09-08 13:47 UTC, aleene commented on taxonomies/ingredients.txt
> -ro:must de struguri
is ok

2020-09-11 01:26 UTC, svensven commented
> All the romanian deletes seem to be ok (checked with a translator).

I think a lot of the deletions are (presumably unintentional) reverts of things I've added recently.

2020-12-07 11:10 UTC, teolemon commented on taxonomies/ingredients.txt
> +pl:Pektyna, pektyna owocowa, pektyna z owoców
```suggestion
pl:Pektyna owocowa, pektyna z owoców
```

2020-12-07 11:11 UTC, teolemon commented on taxonomies/ingredients.txt
> +fr:Starters pour levain
```suggestion
fr:Préparations pour levain, Starters pour levain
```

2020-12-07 11:11 UTC, teolemon commented on taxonomies/ingredients.txt
> +fr:Starters pour levain
I took that from real-life examples in the DB

2020-12-07 11:11 UTC, teolemon commented on taxonomies/ingredients.txt
>  <en:cellulase
```suggestion
<en:cellulase
en:hemicellulase
```

2020-12-07 11:12 UTC, teolemon commented on taxonomies/ingredients.txt
> +de:Milchpulver
```suggestion
```

2020-12-07 11:12 UTC, teolemon commented on taxonomies/ingredients.txt
>  pt:leite em pó
```suggestion
pt:leite em pó
ro:lapte praf
```

2021-01-14 17:19 UTC, teolemon commented
This is stale. We can recover translations from the server anyway.

2021-01-14 17:19 UTC, closed without merging