Added the Israeli Mandatory labels
openfoodfacts/openfoodfacts-server pull request #4611
Opened 2020-12-10 10:35 UTC by yarons

As per #4481

2020-12-10 15:46 UTC, stephanegigandet requested changes
For labels that are specific to a country, if the name is not distinctive (e.g. if the name could be used in other countries as well), then we should probably add the name of the country, so that we don't mix different labels together.

e.g. maybe something like:

en:Green Label - Israel
he:הסימון הירוק
countries:en: en:israel

en:High level of fat - Israel
he:שומן בכמות גבוהה
countries:en: en:israel

2020-12-14 06:24 UTC, yarons commented
Done, anything else I should change?

PS We should really switch to Wikidata :)

2021-01-29 14:11 UTC, teolemon commented
Ok for me. @stephanegigandet needs to approve so that we can merge.

2021-02-10 18:29 UTC, stephanegigandet approved these changes

2021-02-10 18:30 UTC, merged