[Snyk] Security upgrade highcharts from 8.2.2 to 9.0.0
openfoodfacts/openfoodfacts-server pull request #4831
Opened 2021-02-06 07:46 UTC by VaiTon

<h3>Snyk has created this PR to fix one or more vulnerable packages in the `npm` dependencies of this project.</h3>

![merge advice](https://app.snyk.io/badges/merge-advice/?package_manager=npm&package_name=highcharts&from_version=8.2.2&to_version=9.0.0&pr_id=8729d544-d157-40bc-9a91-62807a2211b1&visibility=true&has_feature_flag=false)

#### Changes included in this PR

- Changes to the following files to upgrade the vulnerable dependencies to a fixed version:
    - package.json
    - package-lock.json

#### Vulnerabilities that will be fixed
##### With an upgrade:
Severity                   | Priority Score (*)                   | Issue                   | Breaking Change                   | Exploit Maturity
:-------------------------:|-------------------------|:-------------------------|:-------------------------|:-------------------------
![medium severity](https://res.cloudinary.com/snyk/image/upload/w_20,h_20/v1561977819/icon/m.png "medium severity")  |  **708/1000**  <br/> **Why?** Proof of Concept exploit, Recently disclosed, Has a fix available, CVSS 6.3  | Prototype Pollution <br/>[SNYK-JS-HIGHCHARTS-1018906](https://snyk.io/vuln/SNYK-JS-HIGHCHARTS-1018906) |  Yes  | Proof of Concept 

(*) Note that the real score may have changed since the PR was raised.

<details>
  <summary><b>Commit messages</b></summary>
  </br>
  <details>
    <summary>Package name: <b>highcharts</b></summary>
    The new version differs by 1 commits.</br>
    <ul>
      <li><a href="https://snyk.io/redirect/github/highcharts/highcharts-dist/commit/5db01d74e072c3a493e55a647443b840e3b5d7b6">5db01d7</a> v9.0.0</li>
    </ul>

   <a href="https://snyk.io/redirect/github/highcharts/highcharts-dist/compare/e4c4afe4117eed5b64ed7696de64d45a44e1257b...5db01d74e072c3a493e55a647443b840e3b5d7b6">See the full diff</a>
  </details>
</details>

Check the changes in this PR to ensure they won't cause issues with your project.

------------

**Note:** *You are seeing this because you or someone else with access to this repository has authorized Snyk to open fix PRs.*

For more information:  <img src="https://api.segment.io/v1/pixel/track?data=eyJ3cml0ZUtleSI6InJyWmxZcEdHY2RyTHZsb0lYd0dUcVg4WkFRTnNCOUEwIiwiYW5vbnltb3VzSWQiOiI4NzI5ZDU0NC1kMTU3LTQwYmMtOWE5MS02MjgwN2EyMjExYjEiLCJldmVudCI6IlBSIHZpZXdlZCIsInByb3BlcnRpZXMiOnsicHJJZCI6Ijg3MjlkNTQ0LWQxNTctNDBiYy05YTkxLTYyODA3YTIyMTFiMSJ9fQ==" width="0" height="0"/>
🧐 [View latest project report](https://app.snyk.io/org/openfoodfacts/project/c1a20f20-ca4a-4165-8887-cb374893a522)

🛠 [Adjust project settings](https://app.snyk.io/org/openfoodfacts/project/c1a20f20-ca4a-4165-8887-cb374893a522/settings)

📚 [Read more about Snyk's upgrade and patch logic](https://support.snyk.io/hc/en-us/articles/360003891078-Snyk-patches-to-fix-vulnerabilities)

[//]: # (snyk:metadata:{"prId":"8729d544-d157-40bc-9a91-62807a2211b1","dependencies":[{"name":"highcharts","from":"8.2.2","to":"9.0.0"}],"packageManager":"npm","projectPublicId":"c1a20f20-ca4a-4165-8887-cb374893a522","projectUrl":"https://app.snyk.io/org/openfoodfacts/project/c1a20f20-ca4a-4165-8887-cb374893a522?utm_source=github&utm_medium=fix-pr","type":"auto","patch":[],"vulns":["SNYK-JS-HIGHCHARTS-1018906"],"upgrade":["SNYK-JS-HIGHCHARTS-1018906"],"isBreakingChange":true,"env":"prod","prType":"fix","templateVariants":["updated-fix-title","priorityScore","merge-advice-badge-shown"],"priorityScoreList":[708]})

2021-02-09 22:13 UTC, teolemon approved these changes

2021-02-10 18:20 UTC, stephanegigandet requested changes
This should not be merged until someone tests all the graphs. The last highcharts update broke some graphs for months before we noticed it.

2021-05-14 08:07 UTC, hangy commented
> This should not be merged until someone tests all the graphs. The last highcharts update broke some graphs for months before we noticed it.

https://github.com/openfoodfacts/openfoodfacts-server/pull/4869#pullrequestreview-617019505

2021-06-26 10:30 UTC, hangy commented
Obsoleted by #5331

2021-06-26 10:30 UTC, closed without merging