Translations for the ingredients taxonomy
openfoodfacts/openfoodfacts-server pull request #4986
Opened 2021-03-12 17:59 UTC by teolemon

Translations for the ingredients taxonomy

2021-03-13 16:48 UTC, stephanegigandet approved these changes
I didn't review everything, but the sample diffs I looked at look good.

2021-03-13 16:54 UTC, stephanegigandet requested changes
Many tests fail because of translations of "colza oil" (huile de colza) have been added to "rapeseed oil". If there isn't a specific word for "rapeseed", then we could put "colza oil or canola oil" as the name.

e.g.

en:Rapeseed oil
fr:Huile de colza ou de navette

2021-03-14 11:31 UTC, teolemon commented on taxonomies/ingredients.txt
> +pl:Olej rzepakowy   Linki  Wikidane  Należy:   Olej rzepakowy,
TOFIX

2021-03-14 11:31 UTC, teolemon commented on taxonomies/ingredients.txt
> +es:aceite de colza orgánico, aceite de colza organico,
```suggestion
es:aceite de colza orgánico, aceite de colza organico
```

2021-03-17 12:28 UTC, teolemon commented on taxonomies/ingredients.txt
> +pl:Olej rzepakowy   Linki  Wikidane  Należy:   Olej rzepakowy,
fixed in commit

2021-03-17 12:28 UTC, teolemon commented on taxonomies/ingredients.txt
> +es:aceite de colza orgánico, aceite de colza organico,
fixed in commit

2021-03-17 15:44 UTC, teolemon commented
- [ ] Errors in the ingredients taxonomy definition:
- [ ] ERROR - de:calciumcarbonat already is a synonym of de:e170 for entry en:e170 - de:e170i cannot be mapped to entry en:e170i
- [ ] ERROR - it:carbonato-di-calcio already is a synonym of it:carbonato-di-calcio for entry en:e170 - it:e170i cannot be mapped to entry en:e170i
- [ ] ERROR - he:לציטין already is a synonym of he:e322 for entry en:e322 - he:e322i cannot be mapped to entry en:e322i
- [ ] ERROR - he:מווסת-חומציות already is a synonym of he:מווסת-חומציות for entry en:acidity-regulator - he:e500 cannot be mapped to entry en:e500
- [ ] ERROR - he:נתרן-פחמתי already is a synonym of he:e500 for entry en:e500 - he:e500i cannot be mapped to entry en:e500i
- [ ] ERROR - de:calciumcarbonat already is a synonym of de:e170 for entry en:e170 - de:e170i cannot be mapped to entry en:e170i
- [ ] ERROR - it:carbonato-di-calcio already is a synonym of it:carbonato-di-calcio for entry en:e170 - it:e170i cannot be mapped to entry en:e170i
- [ ] ERROR - de:natriumcitrat already is a synonym of de:e331 for entry en:e331 - de:natriumcitrat cannot be mapped to entry en:sodium-citrate
- [ ] ERROR - et:naatriumtsitraat already is a synonym of et:e331 for entry en:e331 - et:naatriumtsitraat cannot be mapped to entry en:sodium-citrate
- [ ] ERROR - fi:natriumsitraatti already is a synonym of fi:e331 for entry en:e331 - fi:natriumsitraatti cannot be mapped to entry en:sodium-citrate
- [ ] ERROR - hu:nátrium-citrát already is a synonym of hu:e331 for entry en:e331 - hu:nátrium-citrát cannot be mapped to entry en:sodium-citrate
- [ ] ERROR - it:citrato-di-sodio already is a synonym of it:e331 for entry en:e331 - it:citrato-di-sodio cannot be mapped to entry en:sodium-citrate
- [ ] ERROR - sk:citran-sodný already is a synonym of sk:e331 for entry en:e331 - sk:citran-sodný cannot be mapped to entry en:sodium-citrate
- [ ] ERROR - fr:tocopherol already is a synonym of fr:e307a for entry en:e307a - fr:vitamine-e cannot be mapped to entry en:vitamin-e
- [ ] ERROR - el:dl-α-τοκοφερόλη already is a synonym of el:e307a for entry en:e307a - el:dl-α-τοκοφερόλη cannot be mapped to entry en:dl-alpha-tocopherol
- [ ] ERROR - sl:dl-alfa-tokoferol already is a synonym of sl:e307a for entry en:e307a - sl:dl-alfa-tokoferol cannot be mapped to entry en:dl-alpha-tocopherol
- [ ] ERROR - cs:sukcinát already is a synonym of cs:e363 for entry en:e363 - cs:polyethylenglykol-1000 cannot be mapped to entry en:d-alpha-tocopheryl-polyethylene-glycol-1000-succinate
- [ ] ERROR - fi:c-vitamiini already is a synonym of fi:e300 for entry en:e300 - fi:c-vitamiini cannot be mapped to entry en:vitamin-c
- [ ] ERROR - fr:vitamine-c already is a synonym of fr:e300 for entry en:e300 - fr:vitamine-c cannot be mapped to entry en:vitamin-c
- [ ] ERROR - hu:c-vitamin already is a synonym of hu:e300 for entry en:e300 - hu:c-vitamin cannot be mapped to entry en:vitamin-c
- [ ] ERROR - pt:vitamina-c already is a synonym of pt:e300 for entry en:e300 - pt:vitamina-c cannot be mapped to entry en:vitamin-c
- [ ] ERROR - sk:vitamín-c already is a synonym of sk:e300 for entry en:e300 - sk:vitamín-c cannot be mapped to entry en:vitamin-c
- [ ] ERROR - fr:palmitate-d-ascorbyle already is a synonym of fr:e304 for entry en:e304 - fr:l-ascorbyle-6-palmitate cannot be mapped to entry en:l-ascorbyl-6-palmitate
- [ ] ERROR - hu:aszkorbil-palmitát already is a synonym of hu:e304 for entry en:e304 - hu:l-aszkorbil-6-palmitát cannot be mapped to entry en:l-ascorbyl-6-palmitate
- [ ] ERROR - ca:acid-inosinic already is a synonym of ca:e630 for entry en:e630 - ca:acid-inosinic cannot be mapped to entry en:inosine-monophosphate
- [ ] ERROR - de:inosinmonophosphat already is a synonym of de:e630 for entry en:e630 - de:inosinmonophosphat cannot be mapped to entry en:inosine-monophosphate
- [ ] ERROR - es:acido-inosinico already is a synonym of es:e630 for entry en:e630 - es:acido-inosinico cannot be mapped to entry en:inosine-monophosphate
- [ ] ERROR - fi:inosiinimonofosfaatti already is a synonym of fi:e630 for entry en:e630 - fi:inosiinimonofosfaatti cannot be mapped to entry en:inosine-monophosphate
- [ ] ERROR - fr:acide-inosinique already is a synonym of fr:e630 for entry en:e630 - fr:acide-inosinique cannot be mapped to entry en:inosine-monophosphate
- [ ] ERROR - hu:inozinsav already is a synonym of hu:e630 for entry en:e630 - hu:inozinsav cannot be mapped to entry en:inosine-monophosphate
- [ ] ERROR - pt:acido-inosinico already is a synonym of pt:e630 for entry en:e630 - pt:acido-inosinico cannot be mapped to entry en:inosine-monophosphate
- [ ] ERROR - fr:chlorure-de-choline already is a synonym of fr:e1001 for entry en:e1001 - fr:chlorure-de-choline cannot be mapped to entry en:choline-chloride
- [ ] ERROR - es:caroteno already is a synonym of es:e160 for entry en:e160 - es:e160a cannot be mapped to entry en:e160a
- [ ] ERROR - es:monoestearato-de-glicerina already is a synonym of es:e471 for entry en:e471 - es:monoestearato-de-glicerina cannot be mapped to entry en:glycerol-monostearate
- [ ] ERROR - pl:monostearynian-glicerolu already is a synonym of pl:e471 for entry en:e471 - pl:monostearynian-glicerolu cannot be mapped to entry en:glycerol-monostearate
- [ ] ERROR - pl:pektyna already is a synonym of pl:e440a for entry en:e440a - pl:pektyna cannot be mapped to entry en:fruit-pectin
- [ ] ERROR - fi:natriumsakariini already is a synonym of fi:e954 for entry en:e954 - fi:natriumsakariini cannot be mapped to entry fr:e954
- [ ] ERROR - es:fermentos-lacticos-seleccionados already is a synonym of es:fermentos-lacticos for entry en:lactic-ferments - es:fermentos-lacticos-seleccionados cannot be mapped to entry en:selected-lactic-ferments
- [ ] ERROR - fr:lactique already is a synonym of fr:e270 for entry en:e270 - fr:produits-laitiers-et-derivees cannot be mapped to entry en:dairy
- [ ] ERROR - de:gerinnungsmittel already is a synonym of de:koagulat for entry en:coagulant - de:gerinnungsmittel cannot be mapped to entry en:clotting-agents
- [ ] ERROR - de:magermilchjoghurt already is a synonym of de:magermilchjoghurt for entry en:low-fat-yogurt - de:entrahmter-joghurt cannot be mapped to entry en:skimmed-yogurt
- [ ] ERROR - es:yogur-desnatado already is a synonym of es:yogur-desnatado for entry en:skimmed-yogurt - es:yogur-descremado cannot be mapped to entry en:skimmed-mild-yogurt
- [ ] ERROR - de:milchsäure already is a synonym of de:e270 for entry en:e270 - de:milchsäure cannot be mapped to entry en:acid-whey
- [ ] ERROR - de:molkepulver already is a synonym of de:molkepulver for entry en:milk-solids - de:molkenpulver cannot be mapped to entry en:whey-powder
- [ ] ERROR - es:nata-montada already is a synonym of es:nata-montada for entry en:whipping-cream - es:crema-de-leche-montada cannot be mapped to entry en:whipped-cream
- [ ] ERROR - fr:lait-caille already is a synonym of fr:lait-caille for entry en:milk-solids - fr:lait-fermente cannot be mapped to entry en:soured-milk
- [ ] ERROR - ca:formatge-fresc already is a synonym of ca:formatge-blanc-suau for entry en:soft-white-cheese - ca:formatge-fresc cannot be mapped to entry en:fromage-blanc
- [ ] ERROR - fr:retinol already is a synonym of fr:retinol for entry en:retinol - fr:vitamine-a cannot be mapped to entry en:vitamin-a
- [ ] ERROR - de:provitamin-a already is a synonym of de:e160a for entry en:e160a - de:provitamin-a cannot be mapped to entry en:provitamin-a
- [ ] ERROR - sl:tiamin-hidroklorid already is a synonym of sl:tiamin-hidroklorid for entry en:thiamin-hydrochloride - sl:tiamin cannot be mapped to entry en:thiamin
- [ ] ERROR - fr:vitamine-b8 already is a synonym of fr:biotine for entry en:biotin - fr:vitamine-b8 cannot be mapped to entry en:vitamin-b8
- [ ] ERROR - fr:folacine already is a synonym of fr:acide-folique for entry en:folic-acid - fr:folacine cannot be mapped to entry en:folacin
- [ ] ERROR - es:cianocobalamina already is a synonym of es:cianocobalamina for entry en:cyanocobalamin - es:vi [...]

2021-03-24 09:56 UTC, teolemon commented
@stephanegigandet I somehow fixed it, but there are many non blocking errors that are disturbing.

2021-03-24 11:40 UTC, stephanegigandet commented on taxonomies/ingredients.txt
> -fr:Huile de colza
we should add "fr:Huile de colza ou de navette" as the French name of en:rapeseed oil

2021-03-24 11:40 UTC, stephanegigandet approved these changes
I guess we can merge as-is, and then we can review and correct the non blocking errors one by one.

2021-03-24 18:02 UTC, teolemon commented
I guess so. Collecting feedback is important though.

2021-03-24 19:56 UTC, teolemon commented
@stephanegigandet fixed

2021-03-29 09:55 UTC, teolemon commented
Just rebased. Let's merge immediately once it passes @stephanegigandet

2021-03-30 08:25 UTC, merged