Translations for the categories taxonomy
openfoodfacts/openfoodfacts-server pull request #5382
Opened 2021-07-17 09:30 UTC by teolemon

Translations for the categories taxonomy

2021-07-21 20:19 UTC, moon-rabbitOFF requested changes

2021-07-21 20:19 UTC, moon-rabbitOFF commented on taxonomies/categories.txt
> +it:Salsicce di maiale
```suggestion
it:Salsicce di suino
```

2021-07-21 20:19 UTC, moon-rabbitOFF commented on taxonomies/categories.txt
> +it:Salsicce di fegato di maiale
```suggestion
it:Salsicce di fegato di suino
```

2021-07-21 20:19 UTC, moon-rabbitOFF commented on taxonomies/categories.txt
> +pt:Cacau e avelãs para barrar
```suggestion
pt:Creme para barrar de avelã e cacau
```

2021-07-21 20:19 UTC, moon-rabbitOFF commented on taxonomies/categories.txt
> +pt:Avelãs para barrar
```suggestion
pt:Creme para barrar de avelã 
```

2021-07-21 20:19 UTC, moon-rabbitOFF commented on taxonomies/categories.txt
> +pt:Chocolates para barrar
```suggestion
pt:Creme para barrar de chocolate
```

2021-07-21 20:21 UTC, moon-rabbitOFF commented
I think that would be good that someone else with a knowledge of the taxonomy proofreads again this massive update. There are numerous languages that I couldn't review

2023-04-28 19:51 UTC, benbenben2 commented on taxonomies/categories.txt
> +es:Surtido de chocolates, Surtido de chocolatinas, Surtido de bombones
I would keep " Surtido de chocolatinas, Surtido de bombones" as it looks like synonyms. What do you think @moon-rabbitOFF ?

2023-04-28 20:10 UTC, benbenben2 commented on taxonomies/categories.txt
> +tr:Yağ (katı)
```suggestion
tr:Yağ
```

2023-04-28 20:10 UTC, benbenben2 commented on taxonomies/categories.txt
> +tr:Bitkisel yağ (katı)
```suggestion
tr:Bitkisel yağ
```

2023-04-28 20:10 UTC, benbenben2 commented on taxonomies/categories.txt
> +tr:Bitkisel yağlar (sıvı)
```suggestion
tr:Bitkisel yağlar
```

2023-05-10 18:51 UTC, benbenben2 commented
@moon-rabbitOFF , @teolemon I made a local merge with main to resolve all conflicts. Now is the chance to close this pull request!

2023-05-19 05:44 UTC, benbenben2 commented
@moon-rabbitOFF , @teolemon, @stephanegigandet,  I made a local merge with main again to resolve all conflicts. Now is the chance to close this pull request!

2023-05-19 09:35 UTC, stephanegigandet commented
> @moon-rabbitOFF , @teolemon, @stephanegigandet, I made a local merge with main again to resolve all conflicts. Now is the chance to close this pull request!

Wonderful, thank you @benbenben2 !

2023-05-19 09:35 UTC, merged