fix: allow unchecking checked boxes in product edit form
openfoodfacts/openfoodfacts-server pull request #6203
Opened 2021-12-16 13:39 UTC by stephanegigandet

This fixes an issue with my recent refactoring of the code to handle nutrition facts edit from the web product edit form and the API.

The issue is that when a checkbox is unchecked on a form, the browser actually does not send the field at all. So if the parameter is not there, we don't know if it's because it is not set on purpose (e.g. the API is changing something else), or the box is there but has been unset (through the web edit form).

The trick is to add a hidden field with the same name of the checkbox on the web form. That way we do get the hidden value if the box is unchecked, and the checked value if it is checked.

2021-12-17 11:42 UTC, alexgarel requested changes
Does not work for me.

2021-12-17 11:42 UTC, alexgarel commented on templates/web/pages/product_edit/product_edit_form_display.tt.html
> +            <input type="hidden" name="no_nutrition_data" value="" />
Hum this does not work for me !

If I check the box, this is not taken into account.

In Food.pm, in `assign_nutriments_values_from_request_parameters`, `param("no_nutrition_data")` is `''`

2022-01-03 17:02 UTC, stephanegigandet commented
@alexgarel I updated the code to add a new hidden field, as you suggested if I remember correctly.

2022-01-05 14:50 UTC, alexgarel commented on lib/ProductOpener/Food.pm
> +	}
Cool

2022-01-05 15:00 UTC, merged