Remove unary operators
openfoodfacts/openfoodfacts-server pull request #6303
Opened 2022-01-14 14:23 UTC by teolemon

Remove unary operators

2022-01-14 18:22 UTC, alexgarel requested changes
I think you forgot the 1

2022-01-14 18:22 UTC, alexgarel commented on html/js/folksonomy.js
> +        while (index-=) {
```suggestion
        while (index-=1) {
```

2022-01-14 18:22 UTC, alexgarel commented on html/js/folksonomy.js
> +        while (index-=) {
```suggestion
        while (index-=1) {
```

2022-01-14 18:22 UTC, alexgarel commented on html/js/folksonomy.js
> +        while (index-=) {
```suggestion
        while (index-=1) {
```

2022-01-26 13:17 UTC, VaiTon commented
NPM test is failing because of:

```
 /home/runner/work/openfoodfacts-server/openfoodfacts-server/html/js/folksonomy.js
Error:   318:16  error    Expected a conditional expression and instead saw an assignment  no-cond-assign
Error:   377:16  error    Expected a conditional expression and instead saw an assignment  no-cond-assign
Error:   425:16  error    Expected a conditional expression and instead saw an assignment  no-cond-assign
Error:   690:16  error    Expected a conditional expression and instead saw an assignment  no-cond-assign
Warning:   991:13  warning  Unary operator '++' used                                         no-plusplus
```

2022-01-26 15:26 UTC, alexgarel commented
@VaiTon error is related to the PR (you see it in the *Files changed* tab).

Indeed the linter does not like this way of writing. So I think the `index--` was the right way of writing…

@teolemon I would suggest closing this.

2022-01-26 15:28 UTC, teolemon commented
ok

2022-01-26 15:28 UTC, closed without merging