enable gzip_static and gunzip for OCR json files
openfoodfacts/openfoodfacts-server pull request #6347
Opened 2022-01-27 10:19 UTC by stephanegigandet

This is to allow keeping only compressed .json.gz files for OCR results.

Part of #6273

2022-01-27 10:19 UTC, stephanegigandet commented
Once finalized, we'll also need to change the config for the other product opener instances, docker config etc.

2022-01-27 10:57 UTC, cquest commented
No effect, because of https://github.com/openfoodfacts/openfoodfacts-server/pull/6347/files#L160

2022-01-27 10:59 UTC, cquest requested changes
The rule at https://github.com/openfoodfacts/openfoodfacts-server/pull/6347/files#L160 takes precedence... so this change has no effect on OCR json files.

2022-01-27 11:53 UTC, stephanegigandet reviewed
Perfect,.

2022-01-27 15:11 UTC, alexgarel approved these changes
LGTM

2022-02-25 17:11 UTC, teolemon commented
@cquest could you confirm @stephanegigandet's changes suit you to unblock the PR ?

2022-03-15 16:44 UTC, alexgarel commented
@stephanegigandet this is still stalled ? Shan't we also change the perl code to directly store gzipped file for OCR ?

2023-07-25 08:30 UTC, closed without merging