issue-labeler.yml
openfoodfacts/openfoodfacts-server pull request #6459
Opened 2022-03-05 19:53 UTC by teolemon

### Checklist
- issue-labeler.yml

2022-03-07 07:23 UTC, stephanegigandet commented on .github/issue-labeler.yml
> +not done
typo?

2022-03-07 07:38 UTC, stephanegigandet requested changes
issue-labeler can only be used for a very small and specific set of labels that are expected in an issue template.

It's probably not a good match for this repo that has lots of labels.

Even on other repos with fewer labels, please try it with one label at a time, and uncomment the not-before option, so that we can check that it does not break old issues.

Specifically, merging this PR as-is would remove almost all existing labels on almost all issues.

2022-03-07 09:36 UTC, teolemon commented on .github/issue-labeler.yml
> +not done
fixed

2022-03-07 09:55 UTC, teolemon commented
@stephanegigandet I've disabled processing of issues older than today, and enabled a revision mechanism

2022-03-07 11:03 UTC, stephanegigandet commented
@teolemon : this PR will remove most labels entered manually, unless their body also match the exact regexps (including case) listed.

2022-03-07 11:11 UTC, stephanegigandet commented
@teolemon example : I changed the title of this issue https://github.com/openfoodfacts/smooth-app/issues/1166 , and the action removed the ios label, because it is not in the body.

2022-03-22 09:13 UTC, stephanegigandet commented
Closing as issue-labeler does not work as wanted.

2022-03-22 09:13 UTC, closed without merging