feat: Add settings explanations
openfoodfacts/openfoodfacts-server pull request #6799
Opened 2022-05-19 12:25 UTC by teolemon

### What
feat: Add settings explanations

2022-05-19 16:58 UTC, stephanegigandet requested changes
We should not add empty strings for settings explanations, that will have unwanted side effects (e.g. displaying info icons that will lead to a blank screen).

2022-05-19 18:57 UTC, teolemon commented
It's still a WIP that I started during a meeting ;-)

2022-05-20 17:42 UTC, teolemon commented on po/common/common.pot
> +msgid ""
```suggestion
msgid "L'empreinte forêt correspond au risque de déforestation associé à ses ingrédients."
```

2022-05-25 10:45 UTC, teolemon commented on po/common/common.pot
> +msgid ""
```suggestion
msgid "To determine whether an ingredient is vegan, we only rely on the list of ingredients."
```

2022-05-25 10:45 UTC, teolemon commented on po/common/common.pot
> +msgid ""
```suggestion
msgid "To determine whether an ingredient is vegetarian, we only rely on the list of ingredients."
```

2022-05-25 10:46 UTC, teolemon commented on po/common/common.pot
> +msgid "L'empreinte forêt correspond au risque de déforestation associé à ses ingrédients."
```suggestion
msgid "The forest footprint corresponds to the risk of deforestation associated with its ingredients."
```

2022-05-25 10:46 UTC, teolemon commented on po/common/common.pot
> +msgid ""
```suggestion
msgid "To determine whether an ingredient contains palm oil, we only rely on the list of ingredients."
```

2022-05-25 10:47 UTC, teolemon commented on po/common/common.pot
> +msgid "To determine whether an ingredient contains palm oil, we only rely on the list of ingredients."
```suggestion
msgid "To determine whether a product contains palm oil, we only rely on the list of ingredients."
```

2022-05-25 10:47 UTC, teolemon commented on po/common/common.pot
> +msgid "To determine whether an ingredient is vegetarian, we only rely on the list of ingredients."
```suggestion
msgid "To determine whether a product is vegetarian, we only rely on the list of ingredients."
```

2022-05-25 10:47 UTC, teolemon commented on po/common/common.pot
> +msgid "To determine whether an ingredient is vegan, we only rely on the list of ingredients."
```suggestion
msgid "To determine whether a product is vegan, we only rely on the list of ingredients."
```

2022-06-06 16:38 UTC, stephanegigandet approved these changes

2022-06-06 16:41 UTC, teolemon commented on po/common/common.pot
> +msgstr ""
```suggestion
```

2023-06-27 10:13 UTC, alexgarel reviewed
fixing

2023-06-27 10:13 UTC, alexgarel commented on po/common/en.po
> +msgstr ""
```suggestion
msgstr "To determine whether a product is vegan, we only rely on the list of ingredients."
```

2023-06-27 10:13 UTC, alexgarel commented on po/common/en.po
> +msgstr ""
```suggestion
msgstr "To determine whether a product is vegetarian, we only rely on the list of ingredients."
```

2023-06-27 10:13 UTC, alexgarel commented on po/common/en.po
> +msgstr ""
```suggestion
msgstr "To determine whether a product contains palm oil, we only rely on the list of ingredients."
```

2023-06-27 10:41 UTC, merged