feat: add explanation with category in the Nutri-Score and Eco-Score knowledge panels when not applicable
openfoodfacts/openfoodfacts-server pull request #6844
Opened 2022-06-01 14:53 UTC by stephanegigandet

When a product does not have a Nutri-Score or an Eco-Score because the product category is excluded from the Nutri-Score and Eco-Score, we now explain why in the corresponding knowledge panel, and we list the category.

![image](https://user-images.githubusercontent.com/8158668/171434472-841ef7cd-c70f-42a7-ab86-557ab6fdbeef.png)

Fixes https://github.com/openfoodfacts/openfoodfacts-server/issues/6092 and https://github.com/openfoodfacts/openfoodfacts-server/issues/6774

2022-06-02 13:39 UTC, alexgarel requested changes
LGTM but you forgot an image. Also I was expecting a new nutriscore-not-applicable logo ;-)

2022-06-02 13:39 UTC, alexgarel commented on lib/ProductOpener/Attributes.pm
> +		$attribute_ref->{icon_url} = "$static_subdomain/images/attributes/ecoscore-unknown.svg";
you did not include the image, did you ?

2022-06-02 13:39 UTC, alexgarel commented on lib/ProductOpener/Lang.pm
> +
```suggestion

 =head4 target language $target_lc
 
```

2022-06-02 13:45 UTC, alexgarel commented
Also, @stephanegigandet, could be good to add a test for eco-score not applicable…

2022-06-02 13:59 UTC, alexgarel commented
proposal for logo:
![nutriscore-notapplicable](https://user-images.githubusercontent.com/144788/171646471-adc12fe1-59a2-4c42-a22f-0a258ba04d15.svg)

2022-06-02 15:26 UTC, stephanegigandet commented
@alexgarel for the logos, I made a separate PR:
https://github.com/openfoodfacts/openfoodfacts-server/pull/6848/files

Santé publique France has an official logo for "Nutri-Score unknown", so I think we should use it.

I think we can use the same logo for "Nutri-Score not-applicable" as well.

Same for Eco-Score unknown and not-applicable (yet), we can use the same logo.

2022-06-02 15:38 UTC, stephanegigandet commented
> Also, @stephanegigandet, could be good to add a test for eco-score not applicable…

Good point, I added a test.

2022-06-03 08:06 UTC, alexgarel commented on lib/ProductOpener/Attributes.pm
> +		$attribute_ref->{icon_url} = "$static_subdomain/images/attributes/ecoscore-unknown.svg";
will come with #6848

2022-06-03 08:07 UTC, alexgarel approved these changes
Good.

2022-06-03 08:16 UTC, merged