fix: removing the old logos for OBF, OPF, OPFF
openfoodfacts/openfoodfacts-server pull request #7276
Opened 2022-08-30 16:23 UTC by teolemon

### What
- fix: removing the old logo for flavors

### Why
We now have a language independant logo for all flavors, and translators keep translating to logo that don't exist, provoking test failures

### Part of
- #7295

2022-09-02 21:10 UTC, VaiTon requested changes

2022-09-02 21:10 UTC, VaiTon commented on po/common/hi.po
> +msgstr "Hi"
I don't think this is right

2022-09-05 13:39 UTC, teolemon commented on po/openfoodfacts/af.po
> +msgstr "openfoodfacts-logo-af-178x150.png"
```suggestion
msgstr ""
```

2022-09-05 13:39 UTC, teolemon commented on po/openfoodfacts/af.po
> +msgstr "openfoodfacts-logo-af-356x300.png"
```suggestion
msgstr ""
```

2022-09-05 13:41 UTC, teolemon commented
@VaiTon Can you validate ? Also, Please do not remerge l10n_main into this.

2022-09-05 14:04 UTC, VaiTon approved these changes

2022-12-20 16:55 UTC, alexgarel commented
@teolemon why wasn't this branche squasehd and merged ?

2023-05-25 10:00 UTC, merged