chore: Added the logo for the Label Bee Friendly
openfoodfacts/openfoodfacts-server pull request #7360
Opened 2022-09-17 07:18 UTC by pratyaksh1610

### Related issue(s) and discussion

- Fixes #7231

2022-09-19 15:05 UTC, stephanegigandet commented
Could you rename the file to je-protege-les-abeilles.svg to je-protege-les-abeilles.90x90.svg and make the black background transparent?  90x90 indicates the aspect ratio.

2022-09-23 07:57 UTC, alexgarel commented
See https://github.com/openfoodfacts/openfoodfacts-server/issues/7231#issuecomment-1251031479

You have to add the label to the taxonomy, otherwise it won't be displayed.

2022-09-26 15:31 UTC, alexgarel requested changes
thank @pratyaksh1610 
Still one fix to go :-)

2022-09-26 15:31 UTC, alexgarel commented on taxonomies/labels.txt
> +origins:en: en:france
No the meaning of the label is not that honey comes from france

```suggestion
```

2022-09-27 12:29 UTC, merged

2023-01-17 10:16 UTC, manon-corneille commented
Hi guys, (cc @alexgarel)
It seems that the label Bee Friendly is not recognised yet → https://fr.openfoodfacts.org/label/bee-friendly 
Is it related to the " taxonomy rebuild "? 

Thanks :-)