feat: add Totano to ingredients taxonomy
openfoodfacts/openfoodfacts-server pull request #7438
Opened 2022-10-04 15:11 UTC by VaiTon

2022-10-04 17:42 UTC, aleene requested changes
Can you add the english name as well en:European flying squid and the latin name.
On the wikidata page you can also link back to OFF by adding a parameter there.

2022-10-04 17:46 UTC, VaiTon commented
@aleene on wikidata I only see "OpenFoodFacts category". Is there another one for ingredients?

2022-10-04 18:00 UTC, aleene commented
Search for open food (with the space)

2022-10-04 18:07 UTC, aleene requested changes
Language code is la: not lat:

2022-10-04 18:07 UTC, aleene commented
Wonder is we should use the latin name for all fish entries.

2022-10-05 16:13 UTC, VaiTon commented on taxonomies/ingredients.txt
> +lat:todarodes sagittatus
```suggestion
la:todarodes sagittatus
```

2022-10-05 20:01 UTC, aleene approved these changes

2022-10-05 20:30 UTC, merged