doc: improvement to the Images API
openfoodfacts/openfoodfacts-server pull request #7674
Opened 2022-11-09 07:18 UTC by Roxie-32

- Separate the image into 2 schemas (one for the normal image(with a number as the key) and one selected image(eg..packaging_fr))
- Create a request for Images API

2022-11-09 07:20 UTC, Roxie-32 commented
@alexgarel I made another PR for the images API and closed the last one, the commits in the last PR were mixed up. I wasn't so sure if I got the pattern properties section but I made an attempt. I am also unsure of what the regex will be for selected images like front_en etc.

2022-11-09 14:09 UTC, alexgarel requested changes
I would expect to have a description for every field (you may ask on slack for those who are too obscure)

2022-11-09 14:09 UTC, alexgarel commented on docs/reference/api.yml
> +                          packaging_fr:
this also should be a regexp: 

```suggestion
                          '(front|ingredients|nutrition|packaging|other)_\w\w(-\w\w)?:
```

2022-11-09 14:09 UTC, alexgarel commented on docs/reference/schemas/images/image.yaml
> +            example: 56
factor this out (also used in selected_image)

2022-11-11 13:47 UTC, Roxie-32 commented
@alexgarel I think I added all descriptions except for these `coordinates_image_size`, `rev`, `geometry` then `x1, x2....`. I didn't really get them.  Can you review it again and see if there are more corrections? I also factored out the image size(height and width to a separate file.

2022-11-15 14:43 UTC, Roxie-32 commented
> @alexgarel I think I added all descriptions except for these `coordinates_image_size`, `rev`, `geometry` then `x1, x2....`. I didn't really get them. Can you review it again and see if there are more corrections? I also factored out the image size(height and width to a separate file.

@alexgarel @stephanegigandet were you able to see this please?

2022-11-16 10:36 UTC, alexgarel approved these changes
It's already a good improvement, thanks @Roxie-32 

Let's merge it.

2022-11-16 10:37 UTC, merged