docs: add more optional search parameters to open api
openfoodfacts/openfoodfacts-server pull request #7766
Opened 2022-11-28 14:32 UTC by Roxie-32

Add more query parameters to the search open api

2022-11-30 14:50 UTC, alexgarel requested changes
Thanks for the work. Still I propose we improve a bit to make it more useful

2022-12-01 20:54 UTC, Roxie-32 commented on docs/reference/api.yml
> +          The packaging_tag in german of product(s) you are searching for.
@alexgarel you were meant to explain this bette please

2022-12-01 22:55 UTC, Roxie-32 commented on docs/reference/api.yml
> +        The traces_tags of product(s) you are searching for.
Fixed !

2022-12-02 09:09 UTC, stephanegigandet commented on docs/reference/api.yml
> +          The packaging_tag in german of product(s) you are searching for.
@alexgarel very cool indeed :)

2022-12-02 09:14 UTC, stephanegigandet commented on docs/reference/api.yml
> +          The packaging_tag in german of product(s) you are searching for.
> "will search in the `tag_name` tags in the language corresponding to `language_code"

It's a bit different: the language code applies to the values that are passed to the field. e.g. search for categories_tags_fr=moutarde is turned into a search for categories_tags=en:mustard

2022-12-06 10:48 UTC, alexgarel commented on docs/reference/api.yml
> +          The packaging_tag in german of product(s) you are searching for.
@funke, taking into account @stephanegigandet comment:

```yaml
    tagname_with_language_code:
      description: |
        You can add a language code to a specific tag to query it in a specific language
      schema:
        type: Object
        patternProperty:
          (?<tag_name>\w+)_tags_(?<language_code>\w\w): 
            type: string
            description: will search in the `tag_name` tags using `language_code` translation of the tag. tag_name can be: origins, labels, countries, categories, etc. (refer to available parameters ending with `_tags`)
      examples:
        - packaging_tags_de: Flasche      
        - origins_tags_fr: Suisse
 ```

- It adds a parameter, which name is only descriptive (as the real name is defined by the patternProperty inside it), think of this name as an identifier for this type of parameter, so I used `tagname_with_language_code`
- then we use a schema definition of type object (it does not mean the parameter contains an object, it means we define the parameter using an object schema, it's a bit subtle, one as to read [the specification and it's examples](https://spec.openapis.org/oas/latest.html#fixed-fields-9) to really understand that). In our case, the property of the object, would indeed be the name the parameter takes.
- patternProperty enables us to use a regular expression to define property name (which, as stated above, becomes our parameter name). The expression, says we have a first part composed of multiple letters (\w) which is the tag_name (I used capturing expressions, [not sure it's really supported](https://json-schema.org/understanding-json-schema/reference/regular_expressions.html)), then _tags_ then the language code: two letters. If it does not work try with `(\w+)_tags_(\w\w)`

2022-12-06 11:12 UTC, stephanegigandet commented on docs/reference/api.yml
> +        The states_tags in english of product(s) you are searching for.
The states_tags exist on the public platform as well: http://world.openfoodfacts.org/states

2022-12-08 22:36 UTC, Roxie-32 commented on docs/reference/api.yml
> +          The packaging_tag in german of product(s) you are searching for.
@alexgarel, this throws some errors, like the example should match the data type declared. I haven't understood the concept entirely, so its a bit difficult for me. Can you help out?

2022-12-12 22:17 UTC, Roxie-32 commented on docs/reference/api.yml
> +          The packaging_tag in german of product(s) you are searching for.
HI @alexgarel briniging your attention back to this.

2022-12-23 19:11 UTC, alexgarel approved these changes
I did a commit.

Seems like redoc as some hard time rendering the patternProperty, but I think we can merge as is for the moment.

See https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/openfoodfacts/openfoodfacts-server/search-parameters-api-docs/docs/reference/api.yml#tag/Read-Requests/operation/get-search

2023-01-02 09:39 UTC, merged