feat: logo for comcombre de france
openfoodfacts/openfoodfacts-server pull request #7997
Opened 2023-01-16 18:03 UTC by teolemon

### What
feat: logo for comcombre de france

2023-01-17 16:44 UTC, stephanegigandet commented
If the height is not 90px, the logo won't be shown.

2023-01-20 15:52 UTC, alexgarel requested changes
See stephane comment

2023-01-20 16:25 UTC, alexgarel approved these changes
:+1: 
![image](https://user-images.githubusercontent.com/144788/213751029-e2b85384-1c54-40d7-a8aa-13ebf9d49722.png)

2023-01-23 08:52 UTC, stephanegigandet approved these changes
Thanks!

2023-01-23 08:52 UTC, merged