taxonomy: add some structure to data quality
openfoodfacts/openfoodfacts-server pull request #8082
Opened 2023-02-08 15:52 UTC by alexgarel

Add some structure to data quality.

Linked to #7718 and to PR #8032

2023-02-08 16:38 UTC, CharlesNepote requested changes
Great, thanks.

2023-02-08 16:38 UTC, CharlesNepote commented on taxonomies/data_quality.txt
> +description:en:Error on nutrition data (nutriments)
```suggestion
description:en:Error on nutrition data (nutrients)
```

2023-02-09 08:21 UTC, stephanegigandet commented on taxonomies/data_quality.txt
> +description:en: Their might be an issue with fiber nutriment
```suggestion
description:en: There might be an issue with the fibers nutrient
```

2023-02-09 08:22 UTC, stephanegigandet commented on taxonomies/data_quality.txt
> +en:Fiber warnings
```suggestion
en:Fibers warnings
```

2023-02-09 08:52 UTC, diivi commented on taxonomies/data_quality.txt
> +description:en: Food groups can't be infered
```suggestion
description:en: Food groups can't be inferred
```

2023-02-09 14:16 UTC, alexgarel commented on taxonomies/data_quality.txt
> +<en:Carbon footbrint warnings
:sweat_smile: thanks @diivi !

2023-02-09 14:17 UTC, alexgarel commented
Thank you everybody for the attentive reviews ! @CharlesNepote can you approve ?

2023-02-09 15:05 UTC, CharlesNepote approved these changes

2023-02-10 11:57 UTC, merged