Update improvements.txt
openfoodfacts/openfoodfacts-server pull request #8441
Opened 2023-05-21 20:20 UTC by ItshMoh

I have added the Hindi translation of each sentences. These translations are all correct and used in daily life. Kindly merge it. It will be very helpful for hindi speaking people.

### What

### Screenshot

### Related issue(s) and discussion

- Fixes #[ISSUE NUMBER]

2023-05-21 20:34 UTC, ItshMoh commented
please merge it. It was my first open source contribution.

2023-05-29 11:30 UTC, teolemon commented on taxonomies/improvements.txt
> +hi:पोषण      - श्रेणी के लिए अधिक चीनी मात्रा
```suggestion
hi:पोषण - श्रेणी के लिए अधिक चीनी मात्रा
```

2023-05-29 11:30 UTC, teolemon commented on taxonomies/improvements.txt
> +hi:पोषण      - श्रेणी के लिए अधिक चीनी मात्रा
@ItshMoh can you remove the extra spaces like in my example ?

2023-06-02 05:39 UTC, ItshMoh commented
@teolemon i have removed the spaces as you suggested.

2023-06-05 17:55 UTC, alexgarel requested changes
@ItshMoh thank you for your contribution.

But there are some subtleties with taxonomies format:
- you must not had empty line inside an item definition, they are meaningful, a new line starts a new item
- you must not translate properties name

2023-06-05 17:55 UTC, alexgarel commented on taxonomies/improvements.txt
> +वर्णन:hi:सोडियम में 5% से 10% की कमी से न्यूट्री-स्कोर बेहतर होगा।
You have to keep property name in english !

```suggestion
description:hi: सोडियम में 5% से 10% की कमी से न्यूट्री-स्कोर बेहतर होगा।
```

2023-06-05 17:55 UTC, alexgarel commented on taxonomies/improvements.txt
> +वर्णन:hi:संतृप्त वसा में 5% से 10% की कमी से न्यूट्री-स्कोर बेहतर होगा।
```suggestion
description:hi:संतृप्त वसा में 5% से 10% की कमी से न्यूट्री-स्कोर बेहतर होगा।
```

2023-06-05 17:55 UTC, alexgarel commented on taxonomies/improvements.txt
> +वर्णन:hi:प्रोटीन में 5% से 10% की वृद्धि से न्यूट्री-स्कोर बेहतर होगा।
```suggestion
description:hi:प्रोटीन में 5% से 10% की वृद्धि से न्यूट्री-स्कोर बेहतर होगा।
```

2023-06-05 17:55 UTC, alexgarel commented on taxonomies/improvements.txt
> +वर्णन:hi:फाइबर में 5% से 10% की वृद्धि से न्यूट्री-स्कोर बेहतर होगा।
```suggestion
description:hi:फाइबर में 5% से 10% की वृद्धि से न्यूट्री-स्कोर बेहतर होगा।
```

2023-06-05 17:55 UTC, alexgarel commented on taxonomies/improvements.txt
> +
Beware: Don't had new line inside an item definition 

```suggestion
hi:अधिक फाइबर के साथ बेहतर न्यूट्री-स्कोर
```

2023-06-05 17:55 UTC, alexgarel commented on taxonomies/improvements.txt
> +
```suggestion
```

2023-06-05 17:55 UTC, alexgarel commented on taxonomies/improvements.txt
> +
```suggestion
```

2023-06-05 17:55 UTC, alexgarel commented on taxonomies/improvements.txt
> +
```suggestion
```

2023-06-05 17:55 UTC, alexgarel commented on taxonomies/improvements.txt
> +
```suggestion
```

2023-06-05 17:55 UTC, alexgarel commented on taxonomies/improvements.txt
> +वर्णन:hiफलों और सब्जियों में 5% से 10% की वृद्धि से न्यूट्री-स्कोर बेहतर होगा।
```suggestion
description:hiफलों और सब्जियों में 5% से 10% की वृद्धि से न्यूट्री-स्कोर बेहतर होगा।
```

2023-06-05 17:55 UTC, alexgarel commented on taxonomies/improvements.txt
> +
```suggestion
```

2023-06-05 17:55 UTC, alexgarel commented on taxonomies/improvements.txt
> +
```suggestion
```

2023-06-05 17:55 UTC, alexgarel commented on taxonomies/improvements.txt
> +वर्णन:hi:चीनी में 5% से 10% की कमी से न्यूट्री-स्कोर बेहतर होगा।
```suggestion
description:hi:चीनी में 5% से 10% की कमी से न्यूट्री-स्कोर बेहतर होगा।
```

2023-06-05 17:55 UTC, alexgarel commented on taxonomies/improvements.txt
> +
```suggestion
```

2023-06-05 17:55 UTC, alexgarel commented on taxonomies/improvements.txt
> +
```suggestion
```

2023-06-05 17:55 UTC, alexgarel commented on taxonomies/improvements.txt
> +वर्णन:hi:प्रोटीन में 5% या उससे कम की वृद्धि से न्यूट्री-स्कोर बेहतर होगा।
```suggestion
description:hi:प्रोटीन में 5% या उससे कम की वृद्धि से न्यूट्री-स्कोर बेहतर होगा।
```

2023-06-05 17:55 UTC, alexgarel commented on taxonomies/improvements.txt
> +वर्णन:hi:फाइबर  में 5% या उससे कम की वृद्धि से न्यूट्री-स्कोर बेहतर होगा।
```suggestion
description:hi:फाइबर  में 5% या उससे कम की वृद्धि से न्यूट्री-स्कोर बेहतर होगा।
```

2023-06-05 17:55 UTC, alexgarel commented on taxonomies/improvements.txt
> +
```suggestion
```

2023-06-05 17:55 UTC, alexgarel commented on taxonomies/improvements.txt
> +
```suggestion
```

2023-06-05 17:55 UTC, alexgarel commented on taxonomies/improvements.txt
> +वर्णन:hi: फलों और सब्जियों  में 5% या उससे कम की वृद्धि से न्यूट्री-स्कोर बेहतर होगा।
```suggestion
description:hi: फलों और सब्जियों  में 5% या उससे कम की वृद्धि से न्यूट्री-स्कोर बेहतर होगा।
```

2023-06-05 17:56 UTC, alexgarel commented
Please check again your changes after applying my suggestions.

2023-07-10 13:54 UTC, alexgarel commented
@ItshMoh can you remove all the empty lines you introduced ? Or do you need more explanations ?

although I now see my comment above has a terrible mistake… it should read:

> you must not add empty line inside an item definition, they are meaningful, a new line starts a new item

So do not separate properties part from the rest by a blank line !

2023-10-01 09:20 UTC, benbenben2 commented on taxonomies/improvements.txt
> +
```suggestion
```

2023-10-01 09:22 UTC, benbenben2 commented
Hi @alexgarel 
Your suggested changes were applied. Or modified for 1 case.
You can review it, commit suggestion and merge.

2023-10-17 15:49 UTC, alexgarel approved these changes
Thank you so much @ItshMoh !

2023-10-17 15:50 UTC, alexgarel requested changes
let me fix it…

2023-10-17 15:56 UTC, alexgarel approved these changes
There were just some more blank line remaining between items and their descriptions. A regexp change fixed that…

2023-10-19 13:16 UTC, merged