docs: remove off:off references in the API documentation
openfoodfacts/openfoodfacts-server pull request #8680
Opened 2023-07-11 07:27 UTC by albatrousse

removal of the off:off references in the API documentation

2023-07-11 10:24 UTC, alexgarel requested changes
Hum, you did it too literally ! 

Try again ;-)

2023-07-11 10:24 UTC, alexgarel commented on docs/api/index.md
> +> **Warning**: The staging environment has an extra level of [HTTP Basic Authentication][basic_auth] (username: `off`, password: `off`). When making API requests to staging, you may use [https://@wor
You have to remove all the paragraph !

2023-07-11 10:24 UTC, alexgarel commented on docs/api/ref/api-v3.yml
> +    url: 'https://@world.openfoodfacts.net'
you have to remove the '@' (also in the other places)

2023-07-11 10:24 UTC, alexgarel commented on docs/api/tutorial-uploading-photo-to-a-product.md
> +curl -XPOST -u   https://world.openfoodfacts.net/cgi/product_image_upload.pl \
remove the -u also ! (see curl manpage)

2023-07-11 10:26 UTC, alexgarel commented on docs/api/ref/api-v3.yml
> +    url: 'https://@world.openfoodfacts.net'
https://developer.mozilla.org/fr/docs/Web/HTTP/Authentication#acc%C3%A8s_avec_identifiants_dans_lurl

2023-07-11 10:27 UTC, albatrousse commented
Oh my bad, I just did it like a robot @.@. I will correct this right now

2023-07-11 14:58 UTC, stephanegigandet approved these changes
Looks good, thank you!

2023-07-12 08:54 UTC, alexgarel approved these changes
Thanks

2023-07-12 08:55 UTC, merged