fix: add xx: entries to all additives
openfoodfacts/openfoodfacts-server pull request #8939
Opened 2023-09-01 16:57 UTC by stephanegigandet

Add an xx: entry to all additives, this helps additive recognition and ingredients parsing when we don't have a translation.

Fixes #8918

2023-09-01 19:50 UTC, teolemon approved these changes

2023-09-04 13:06 UTC, alexgarel approved these changes
LGTM

2023-09-04 13:06 UTC, alexgarel commented on scripts/snippets/add_xx_entry_to_additives.pl
> +>>>>>>> 601aff8ec564a21a04129e5855b17895f6046016
Do you want to keep those ?

```suggestion
    if ($line =~ /^\w\w:(E(?:[^,]+))/) {
        $e_number = $1;
        chomp($e_number);
    }
    if ((defined $e_number) and ($line =~ /^(#|e_number:|wikidata|efsa)/)) {
        print "xx:$e_number\n";
        $e_number = undef;
    }
```

2023-09-04 13:30 UTC, teolemon commented on scripts/snippets/add_xx_entry_to_additives.pl
> +<<<<<<< HEAD
warning ⚠️

2023-09-04 13:31 UTC, teolemon requested changes
Merge tag issue

2023-09-05 10:54 UTC, teolemon approved these changes

2023-09-05 11:08 UTC, merged