chore: week 43 taxonomy changes
openfoodfacts/openfoodfacts-server pull request #9239
Opened 2023-11-03 14:15 UTC by aleene

### What
More improvements

2023-11-03 17:16 UTC, benbenben2 commented on taxonomies/ingredients_processing.txt
> +nl:geplette
<en:agglomerated
en:rolled
de:gerollt, gerollte, gerollter, gerolltes
es:arrollada,arrollado
pt:enrolado, enrolada, enrolados, enroladas

2023-11-03 17:17 UTC, benbenben2 requested changes
Everything fine except "rolled" that was already in the taxonomy

2023-11-03 17:50 UTC, aleene commented
Ok , I revert the change

2023-11-03 21:08 UTC, benbenben2 approved these changes
All good

2023-11-03 21:08 UTC, merged

2023-11-04 08:10 UTC, aleene commented
@stephanegigandet I  can not find the file where the fail occurs. Could this be added to the test log?