taxonomy: data quality translations
openfoodfacts/openfoodfacts-server pull request #9480
Opened 2023-12-05 17:40 UTC by teolemon

### What
taxonomy: data quality translations

2023-12-05 17:41 UTC, teolemon commented on taxonomies/data_quality.txt
> +=======
```suggestion
```

2023-12-05 17:41 UTC, teolemon commented on taxonomies/data_quality.txt
> +>>>>>>> Stashed changes
```suggestion

```

2023-12-05 17:42 UTC, teolemon commented on taxonomies/data_quality.txt
> +=======
```suggestion

```

2023-12-05 17:42 UTC, teolemon commented on taxonomies/data_quality.txt
> +>>>>>>> Stashed changes
```suggestion

```

2023-12-05 17:42 UTC, teolemon commented on taxonomies/data_quality.txt
> +=======
```suggestion
<en:Nutrition warnings
```

2023-12-05 17:42 UTC, teolemon commented on taxonomies/data_quality.txt
> +>>>>>>> Stashed changes
```suggestion
```

2023-12-05 17:43 UTC, teolemon commented on taxonomies/data_quality.txt
> +=======
```suggestion
```

2023-12-05 17:43 UTC, teolemon commented on taxonomies/data_quality.txt
> +>>>>>>> Stashed changes
```suggestion

```

2023-12-11 21:01 UTC, benbenben2 commented on taxonomies/data_quality.txt
> +
Same as previous comment. This is error, it should be in the first part of the file around line 811

```suggestion
```

2023-12-11 21:02 UTC, benbenben2 requested changes
Almost perfect, just error and warning should not be mixed up. See comments.

2023-12-19 17:19 UTC, benbenben2 approved these changes
all good

2023-12-19 17:19 UTC, merged