Harmonize handling of JS
openfoodfacts/openfoodfacts-server pull request #9900
Opened 2024-03-11 23:37 UTC by mike-lu1

### What
I have replaced the occurrence of `<script src="https://static.openfoodfacts.org/js` and <script src="https://static.openfoodfacts.org<script src="/js with  `<script src="[% static_subdomain %]/js`

### Screenshot

[Screencast from 12-03-24 02:32:02.webm](https://github.com/openfoodfacts/openfoodfacts-server/assets/162586393/101b03d9-f50b-437a-826f-16aece88a43f)

### Related issue(s) and discussion

- Fixes #[9374]

2024-03-11 23:43 UTC, mike-lu1 commented
hey @stephanegigandet @alexgarel kindly review this.

2024-03-12 13:48 UTC, stephanegigandet commented on cgi/import_photos_upload.pl
> +    <script src="[% static_subdomain %]/js/dist/tmpl.js"></script>
[% static_subdomain %] only works for templates that are processed by Template::Toolkit (files in /templates/).

In Perl code, you need to use $static_subdomain instead

2024-03-12 13:49 UTC, stephanegigandet requested changes
If you try it locally, there are JS errors in the console because the files can't be loaded:

crostata-artigianale-forno-miotti:2862          GET http://fr.openfoodfacts.localhost/produit/8033162870633/[%%20static_subdomain%20%]/js/product-search.js net::ERR_ABORTED 400 (Bad Request)

in the source generated:

<script src="[[% static_subdomain %]/js/product-preferences.js](http://fr.openfoodfacts.localhost/produit/8033162870633/[%%20static_subdomain%20%]/js/product-preferences.js)"></script>
<script src="[[% static_subdomain %]/js/product-search.js](http://fr.openfoodfacts.localhost/produit/8033162870633/[%%20static_subdomain%20%]/js/product-search.js)"></script>

Could you try to fix it and then test it locally to verify there are no JS errors?

2024-03-12 14:36 UTC, hangy commented on html/donate/aa.html
> +    <script src="[% static_subdomain %]/js/dist/jquery.js"></script>
The static pages in `html/donate` cannot use the `Template::Toolkit` variables. They probably need to stay as-is

2024-03-14 19:29 UTC, mike-lu1 commented
> Could you try to fix it and then test it locally to verify there are no JS errors?

@stephanegigandet the `products-history.js` is having some persistent jQuery error `Uncaught ReferenceError: $ is not defined`
I have have tweaked the function in most of the ways i know but this has actually not worked for me 

At the parent function ie fist reference of the `$` in the .js file, i don't get the error but i appears in child functions

2024-03-15 10:48 UTC, stephanegigandet commented
> @stephanegigandet the `products-history.js` is having some persistent jQuery error `Uncaught ReferenceError: $ is not defined`

This is a bug unrelated to your changes. It was fixed in this PR: https://github.com/openfoodfacts/openfoodfacts-server/pull/9909

If you update your branch with the main branch, it should solve this error.

2024-03-17 08:08 UTC, mike-lu1 commented
thank you @hangy @stephanegigandet.  I have implemented the above suggestions

2024-03-18 09:25 UTC, stephanegigandet commented on cgi/product_multilingual.pl
> +<script type="text/javascript" src="/js/dist/product-history.js"></script>
I don't think this one should be removed.

2024-03-19 13:30 UTC, stephanegigandet approved these changes
Thank you!

2024-03-19 14:01 UTC, merged