taxonomy: correction cranberry lingonberry
openfoodfacts/openfoodfacts-server pull request #9907
Opened 2024-03-12 21:36 UTC by moon-rabbitOFF

### What

### Screenshot

### Related issue(s) and discussion

- Fixes #[ISSUE NUMBER]

2024-03-13 09:14 UTC, alexgarel approved these changes
Thanks

2024-03-13 09:50 UTC, stephanegigandet commented on taxonomies/food/ingredients.txt
> +fr:airelle rouge
```suggestion
fr:airelle rouge, airelles rouges
```

2024-03-13 10:28 UTC, stephanegigandet requested changes
@moon-rabbitOFF We have about one hundred products that list "airelles" as one of their ingredients: https://fr.openfoodfacts.org/cgi/search.pl?search_terms=airelles&search_simple=1&action=process

It seems that in most cases, "airelles" is used for "cranberries" / "canneberges", so I think it would make sense to keep it as a synonym of en:cranberry

2024-03-19 13:34 UTC, stephanegigandet commented on taxonomies/food/ingredients.txt
> +en:wild lingoberry
```suggestion
en:wild lingonberry, wild lingonberries
```

2024-03-19 13:38 UTC, stephanegigandet approved these changes
Thanks!

2024-03-26 16:18 UTC, merged