refactor: Tags.pm: do not build or load taxonomies on the fly / at module load - remove special case for nutrient_levels.txt
openfoodfacts/openfoodfacts-server pull request #9964
Opened 2024-03-19 18:50 UTC by stephanegigandet

This PR is to simplify taxonomy building and loading, to remove potential chicken and egg problems (to generate the nutrient_levels.txt source file), and to remove potential race conditions when multiple processes try to load and build taxonomies in parallel.

Changes:
- taxonomies/nutrient_levels.txt is now generated only on demand, with script/taxonomies/generators/gen_nutrient_levels_taxonomy.pl : it is commited in the GitHub repository, and we can generate it from time to time (when the nutrients.txt taxonomy changes, or when we have new translations). It does not have to be up to date, this taxonomy is used only for display, so it does not matter if it is slightly out of date.
- the above removes the need for handling nutrient_levels.txt as a special case
- taxonomies are not automatically loaded by just loading the Tags.pm module. This is needed in order to be able to remove on the fly taxonomy building.
- when loading taxonomies, they are not automatically built on the fly, this is error prone and can lead to race conditions. Whenever we deploy a new version, we should build taxonomies once.
- initialization code in modules like Food.pm, EcoScore.pm, GS1.pm etc. that requires taxonomies to be loaded has been moved to dedicated init functions, so that the corresponding code is not automatically run when the module is loaded.

2024-03-20 08:32 UTC, alexgarel commented
Did you forget the script in scripts/taxonomies/generators/ ?

2024-03-20 08:35 UTC, alexgarel commented
Also we should eventually change the apache startup script so that it call every init_ that needs to be called to avoid calling them again and again in children process.

2024-03-20 09:05 UTC, alexgarel requested changes
I think we miss the script :-)

2024-03-21 13:32 UTC, alexgarel commented on Makefile
> +tests: build_lang_test build_taxonomies_test unit_test integration_test
Oooooh good catch, now that we stores built taxonomies as data, this is needed…

2024-03-21 13:51 UTC, stephanegigandet commented on lib/ProductOpener/Ecoscore.pm
> +	}
Sounds good, thanks :)

2024-03-21 15:40 UTC, stephanegigandet commented
> Also we should eventually change the apache startup script so that it call every init_ that needs to be called to avoid calling them again and again in children process.

it's done through the ProductOpener::LoadData::load_data() function called from the startup script (and other scripts)

2024-03-23 09:40 UTC, alexgarel commented on Makefile
> +	mkdir -p logs/apache2 debug html/data || ( whoami; ls -l . ; false )
We must not remove logs/nginx

It might be that we must add create_folders as a dependency to another entry if you have a permission error on that.

2024-03-23 13:21 UTC, alexgarel approved these changes
Cool !

2024-03-23 13:21 UTC, alexgarel commented on scripts/taxonomies/generators/gen_nutrient_levels_taxonomy.pl
> +use strict;
Why not `use ProductOpener::PerlStandards;` ?

2024-03-23 13:55 UTC, merged